// mobile/src/components/DynamicForm.tsx
import { Ionicons } from '@expo/vector-icons';
import * as DocumentPicker from 'expo-document-picker';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import type { RegistrationField, RegistrationForm, RegistrationSection } from '../api/types';
import { colors, font, radius, spacing } from '../theme';
import { MAX_LENGTHS, UPPERCASE_TYPES, formatErrorFor } from '../validation/formats';
import { Card, Chip, Field } from './ui';
import { CheckboxGroup, Picker, RadioGroup, Switch } from './Picker';

export type FormValue = string | string[] | boolean | null;
export type FormValues = Record<string, FormValue>;

/** Everything the caller needs back from the renderer. */
export interface DynamicFormState {
  values: FormValues;
  errors: Record<string, string>;
  setValue: (key: string, value: FormValue) => void;
  validate: () => boolean;
  /** Answers shaped the way the API expects them. */
  payload: () => Record<string, unknown>;
  /** How many times a repeating section is currently filled in. */
  entryCount: (section: RegistrationSection) => number;
  addEntry: (section: RegistrationSection) => void;
  removeEntry: (section: RegistrationSection, index: number) => void;
}

/**
 * Separates the parts of a stored key. A unit separator, because a field key
 * is typed by an administrator and could contain anything printable.
 */
const SEP = '\u001f';

/** Where a repeating section's entries are stored. */
export function sectionKeyOf(section: RegistrationSection): string {
  return section.key?.trim() || `section${section.id}`;
}

/**
 * Every answer lives in one flat map, including the ones inside a repeating
 * section — those are held under section, entry number and field, and only
 * gathered into a list when the form is submitted. One map means the field
 * renderer, the errors and the change handler all work unchanged whether a
 * field is answered once or five times.
 */
export function storageKey(
  section: RegistrationSection,
  index: number | null,
  fieldKey: string,
): string {
  return index === null ? fieldKey : `${sectionKeyOf(section)}${SEP}${index}${SEP}${fieldKey}`;
}

function defaultFor(field: RegistrationField): FormValue {
  if (field.type === 'multiselect') return [];
  if (field.type === 'checkbox') return false;
  return '';
}

const asText = (value: FormValue): string => {
  if (value === null || value === undefined) return '';
  if (Array.isArray(value)) return value.join(',');
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  return value;
};

const minOf = (section: RegistrationSection) => Math.max(0, section.minEntries ?? 1);
const maxOf = (section: RegistrationSection) => Math.max(1, section.maxEntries ?? 10);

/** What one entry is called, falling back to the section's own title. */
export function entryNoun(section: RegistrationSection): string {
  return section.itemLabel?.trim() || section.title;
}

/**
 * Holds the answers for a Super Admin designed form and validates them with the
 * same rules the API enforces, so the applicant is corrected before they submit.
 */
export function useDynamicForm(form: RegistrationForm | null): DynamicFormState {
  const [values, setValues] = useState<FormValues>({});
  const [errors, setErrors] = useState<Record<string, string>>({});
  /** How many entries each repeating section is showing, by section key. */
  const [counts, setCounts] = useState<Record<string, number>>({});

  const liveSections = useMemo(
    () => (form?.sections ?? []).filter((section) => section.isEnabled),
    [form],
  );

  const fieldsOf = useCallback(
    (section: RegistrationSection) => section.fields.filter((field) => field.isEnabled),
    [],
  );

  /* A repeating section opens with the fewest entries it is allowed to have,
     and never fewer than one, so the applicant has something to type into. */
  useEffect(() => {
    setCounts((current) => {
      const next = { ...current };
      let changed = false;
      for (const section of liveSections) {
        if (!section.isRepeatable) continue;
        const key = sectionKeyOf(section);
        if (next[key] === undefined) {
          next[key] = Math.max(minOf(section), 1);
          changed = true;
        }
      }
      return changed ? next : current;
    });
  }, [liveSections]);

  const entryCount = useCallback(
    (section: RegistrationSection) =>
      section.isRepeatable ? (counts[sectionKeyOf(section)] ?? Math.max(minOf(section), 1)) : 1,
    [counts],
  );

  const setValue = useCallback((key: string, value: FormValue) => {
    setValues((current) => ({ ...current, [key]: value }));
    setErrors((current) => {
      if (!current[key]) return current;
      const next = { ...current };
      delete next[key];
      return next;
    });
  }, []);

  const addEntry = useCallback((section: RegistrationSection) => {
    const key = sectionKeyOf(section);
    setCounts((current) => {
      const shown = current[key] ?? Math.max(minOf(section), 1);
      if (shown >= maxOf(section)) return current;
      return { ...current, [key]: shown + 1 };
    });
    setErrors((current) => {
      if (!current[key]) return current;
      const next = { ...current };
      delete next[key];
      return next;
    });
  }, []);

  /**
   * Removing an entry shuffles the ones after it down, so the answers move
   * with them rather than the wrong entry appearing to have been deleted.
   */
  const removeEntry = useCallback(
    (section: RegistrationSection, index: number) => {
      const key = sectionKeyOf(section);
      const fields = fieldsOf(section);

      setCounts((current) => {
        const shown = current[key] ?? Math.max(minOf(section), 1);
        if (shown <= Math.max(minOf(section), 1)) return current;

        setValues((answers) => {
          const next = { ...answers };
          for (let at = index; at < shown - 1; at++) {
            for (const field of fields) {
              const here = storageKey(section, at, field.key);
              const after = storageKey(section, at + 1, field.key);
              if (after in next) next[here] = next[after];
              else delete next[here];
            }
          }
          for (const field of fields) delete next[storageKey(section, shown - 1, field.key)];
          return next;
        });

        return { ...current, [key]: shown - 1 };
      });
    },
    [fieldsOf],
  );

  /**
   * A conditional field only counts when its trigger answer matches. Inside a
   * repeating section the trigger is that entry's own answer; a trigger
   * outside the section is the same for every entry.
   */
  const isVisible = useCallback(
    (
      field: RegistrationField,
      section: RegistrationSection,
      index: number | null,
      source: FormValues,
    ): boolean => {
      if (!field.visibleWhenFieldKey) return true;
      const scoped = storageKey(section, index, field.visibleWhenFieldKey);
      const raw = scoped in source ? source[scoped] : source[field.visibleWhenFieldKey];
      const trigger = asText(raw ?? null);
      const wanted = field.visibleWhenValues ?? [];
      if (wanted.length === 0) return true;
      return wanted.some((candidate) => candidate.toLowerCase() === trigger.toLowerCase());
    },
    [],
  );

  const checkField = useCallback(
    (
      field: RegistrationField,
      key: string,
      found: Record<string, string>,
      source: FormValues,
    ) => {
      const raw = source[key] ?? defaultFor(field);
      const text = asText(raw);
      const empty = Array.isArray(raw) ? raw.length === 0 : text.trim() === '' || text === 'false';

      if (field.validation.required && empty) {
        found[key] = `${field.label} is required.`;
        return;
      }
      if (empty) return;

      const formatError = formatErrorFor(field.type, text);
      if (formatError) {
        found[key] = formatError;
        return;
      }

      const { minLength, maxLength, min, max, pattern } = field.validation;
      if (minLength && text.length < minLength) {
        found[key] = `Minimum ${minLength} characters.`;
      } else if (maxLength && text.length > maxLength) {
        found[key] = `Maximum ${maxLength} characters.`;
      } else if (field.type === 'number' && (min !== null || max !== null)) {
        const numeric = Number(text);
        if (Number.isNaN(numeric)) found[key] = 'Enter a number.';
        else if (min !== null && min !== undefined && numeric < min) {
          found[key] = `Minimum value is ${min}.`;
        } else if (max !== null && max !== undefined && numeric > max) {
          found[key] = `Maximum value is ${max}.`;
        }
      } else if (pattern) {
        try {
          if (!new RegExp(pattern).test(text)) {
            found[key] = `Enter a valid ${field.label.toLowerCase()}.`;
          }
        } catch {
          /* A bad pattern on the definition must not block the applicant. */
        }
      }
    },
    [],
  );

  const validate = useCallback((): boolean => {
    const found: Record<string, string> = {};

    for (const section of liveSections) {
      const fields = fieldsOf(section);

      if (!section.isRepeatable) {
        for (const field of fields) {
          if (!isVisible(field, section, null, values)) continue;
          checkField(field, field.key, found, values);
        }
        continue;
      }

      const shown = entryCount(section);
      if (shown < minOf(section)) {
        found[sectionKeyOf(section)] =
          minOf(section) === 1
            ? `Add at least one ${entryNoun(section).toLowerCase()}.`
            : `Add at least ${minOf(section)} of these.`;
        continue;
      }

      for (let index = 0; index < shown; index++) {
        for (const field of fields) {
          if (!isVisible(field, section, index, values)) continue;
          checkField(field, storageKey(section, index, field.key), found, values);
        }
      }
    }

    setErrors(found);
    return Object.keys(found).length === 0;
  }, [liveSections, fieldsOf, entryCount, values, isVisible, checkField]);

  const payload = useCallback((): Record<string, unknown> => {
    const answerOf = (field: RegistrationField, key: string): FormValue => {
      const raw = values[key] ?? defaultFor(field);
      return typeof raw === 'string' && UPPERCASE_TYPES.includes(field.type)
        ? raw.toUpperCase()
        : raw;
    };

    const result: Record<string, unknown> = {};

    for (const section of liveSections) {
      const fields = fieldsOf(section);

      if (!section.isRepeatable) {
        for (const field of fields) {
          if (!isVisible(field, section, null, values)) continue;
          result[field.key] = answerOf(field, field.key);
        }
        continue;
      }

      const entries: Record<string, FormValue>[] = [];
      for (let index = 0; index < entryCount(section); index++) {
        const entry: Record<string, FormValue> = {};
        for (const field of fields) {
          if (!isVisible(field, section, index, values)) continue;
          entry[field.key] = answerOf(field, storageKey(section, index, field.key));
        }
        entries.push(entry);
      }
      result[sectionKeyOf(section)] = entries;
    }

    return result;
  }, [liveSections, fieldsOf, entryCount, values, isVisible]);

  return { values, errors, setValue, validate, payload, entryCount, addEntry, removeEntry };
}

/* ------------------------------------------------------------- renderer */

export function DynamicFormView({
  form,
  state,
}: {
  form: RegistrationForm;
  state: DynamicFormState;
}) {
  const { values, errors, setValue, entryCount, addEntry, removeEntry } = state;

  const visible = (
    field: RegistrationField,
    section: RegistrationSection,
    index: number | null,
  ): boolean => {
    if (!field.visibleWhenFieldKey) return true;
    const scoped = storageKey(section, index, field.visibleWhenFieldKey);
    const raw = scoped in values ? values[scoped] : values[field.visibleWhenFieldKey];
    const trigger = asText(raw ?? null);
    const wanted = field.visibleWhenValues ?? [];
    if (wanted.length === 0) return true;
    return wanted.some((candidate) => candidate.toLowerCase() === trigger.toLowerCase());
  };

  const renderFields = (section: RegistrationSection, index: number | null) => {
    const fields = section.fields.filter((field) => field.isEnabled && visible(field, section, index));
    return fields.map((field) => {
      const key = storageKey(section, index, field.key);
      return (
        <FieldRenderer
          key={key}
          field={field}
          value={values[key] ?? defaultFor(field)}
          error={errors[key]}
          onChange={(value) => setValue(key, value)}
        />
      );
    });
  };

  return (
    <View style={styles.stack}>
      {form.sections
        .filter((section) => section.isEnabled)
        .map((section) => {
          const live = section.fields.filter((field) => field.isEnabled);
          if (live.length === 0) return null;

          if (!section.isRepeatable) {
            const rendered = renderFields(section, null);
            if (rendered.length === 0) return null;

            return (
              <Card key={section.id} style={styles.section}>
                <View style={styles.sectionHeader}>
                  <Text style={styles.sectionTitle}>{section.title}</Text>
                  <Chip>{`${rendered.length} fields`}</Chip>
                </View>
                {section.description ? (
                  <Text style={styles.sectionDescription}>{section.description}</Text>
                ) : null}
                <View style={styles.fields}>{rendered}</View>
              </Card>
            );
          }

          const shown = entryCount(section);
          const noun = entryNoun(section);
          const floor = Math.max(minOf(section), 1);
          const sectionError = errors[sectionKeyOf(section)];

          return (
            <Card key={section.id} style={styles.section}>
              <View style={styles.sectionHeader}>
                <Text style={styles.sectionTitle}>{section.title}</Text>
                <Chip>{`${shown} of ${maxOf(section)}`}</Chip>
              </View>
              {section.description ? (
                <Text style={styles.sectionDescription}>{section.description}</Text>
              ) : null}

              {Array.from({ length: shown }, (_, index) => (
                <View key={index} style={styles.entry}>
                  <View style={styles.entryHeader}>
                    <Text style={styles.entryTitle}>{`${noun} ${index + 1}`}</Text>
                    {shown > floor ? (
                      <Pressable
                        accessibilityRole="button"
                        accessibilityLabel={`Remove ${noun.toLowerCase()} ${index + 1}`}
                        hitSlop={8}
                        onPress={() => removeEntry(section, index)}
                      >
                        <Ionicons name="trash-outline" size={18} color={colors.danger500} />
                      </Pressable>
                    ) : null}
                  </View>
                  <View style={styles.fields}>{renderFields(section, index)}</View>
                </View>
              ))}

              {sectionError ? <Text style={styles.sectionError}>{sectionError}</Text> : null}

              {shown < maxOf(section) ? (
                <Pressable
                  accessibilityRole="button"
                  style={styles.addEntry}
                  onPress={() => addEntry(section)}
                >
                  <Ionicons name="add-circle-outline" size={18} color={colors.brand600} />
                  <Text style={styles.addEntryText}>{`Add ${noun.toLowerCase()}`}</Text>
                </Pressable>
              ) : (
                <Text style={styles.sectionDescription}>
                  {`You can add up to ${maxOf(section)}.`}
                </Text>
              )}
            </Card>
          );
        })}
    </View>
  );
}

function FieldRenderer({
  field,
  value,
  error,
  onChange,
}: {
  field: RegistrationField;
  value: FormValue;
  error?: string;
  onChange: (value: FormValue) => void;
}) {
  const options = field.options.map((option) => ({
    value: option.value,
    label: option.label,
  }));

  switch (field.type) {
    case 'select':
      return (
        <Picker
          label={field.label}
          required={field.validation.required}
          value={typeof value === 'string' ? value : null}
          options={options}
          error={error}
          hint={field.helpText}
          onChange={onChange}
        />
      );

    case 'multiselect':
      return (
        <CheckboxGroup
          label={field.label}
          required={field.validation.required}
          options={options}
          values={Array.isArray(value) ? value : []}
          error={error}
          onChange={onChange}
        />
      );

    case 'radio':
      return (
        <RadioGroup
          label={field.label}
          required={field.validation.required}
          options={options}
          value={typeof value === 'string' ? value : null}
          error={error}
          onChange={onChange}
        />
      );

    case 'checkbox':
      return (
        <Switch
          label={field.helpText || field.label}
          required={field.validation.required}
          checked={value === true}
          error={error}
          onChange={onChange}
        />
      );

    case 'file':
      return (
        <FileField
          field={field}
          value={typeof value === 'string' ? value : ''}
          error={error}
          onChange={onChange}
        />
      );

    case 'textarea':
      return (
        <Field
          label={field.label}
          required={field.validation.required}
          value={typeof value === 'string' ? value : ''}
          onChangeText={onChange}
          placeholder={field.placeholder}
          hint={field.helpText}
          error={error}
          multiline
          numberOfLines={4}
          style={styles.textarea}
        />
      );

    default: {
      const upper = UPPERCASE_TYPES.includes(field.type);
      const numeric = ['number', 'mobile', 'aadhaar', 'pincode'].includes(field.type);

      return (
        <Field
          label={field.label}
          required={field.validation.required}
          value={typeof value === 'string' ? value : ''}
          onChangeText={(text) => onChange(upper ? text.toUpperCase() : text)}
          placeholder={field.placeholder ?? (field.type === 'date' ? 'YYYY-MM-DD' : undefined)}
          hint={field.helpText}
          error={error}
          autoCapitalize={upper ? 'characters' : field.type === 'email' ? 'none' : 'sentences'}
          autoCorrect={false}
          keyboardType={
            numeric ? 'number-pad' : field.type === 'email' ? 'email-address' : 'default'
          }
          maxLength={MAX_LENGTHS[field.type] ?? field.validation.maxLength ?? undefined}
        />
      );
    }
  }
}

/**
 * Picks a document and records its name. The file itself is uploaded to the
 * application once it exists, which is why only the name is held here.
 */
function FileField({
  field,
  value,
  error,
  onChange,
}: {
  field: RegistrationField;
  value: string;
  error?: string;
  onChange: (value: string) => void;
}) {
  const [busy, setBusy] = useState(false);

  const pick = async () => {
    setBusy(true);
    try {
      const extensions = field.validation.allowedExtensions ?? [];
      const result = await DocumentPicker.getDocumentAsync({
        multiple: false,
        copyToCacheDirectory: true,
        type: extensions.length ? extensions.map(mimeFor) : '*/*',
      });
      if (!result.canceled && result.assets[0]) onChange(result.assets[0].name);
    } finally {
      setBusy(false);
    }
  };

  const limits = [
    field.validation.allowedExtensions?.length
      ? field.validation.allowedExtensions.join(', ').toUpperCase()
      : null,
    field.validation.maxFileSizeMb ? `up to ${field.validation.maxFileSizeMb} MB` : null,
  ]
    .filter(Boolean)
    .join(' · ');

  return (
    <View style={styles.fileField}>
      <Text style={styles.fileLabel}>
        {field.label}
        {field.validation.required ? <Text style={styles.required}> *</Text> : null}
      </Text>
      <Pressable
        accessibilityRole="button"
        onPress={pick}
        style={[styles.fileBox, !!error && styles.fileBoxInvalid]}
      >
        <Ionicons
          name={value ? 'document-text-outline' : 'cloud-upload-outline'}
          size={18}
          color={value ? colors.brand700 : colors.ink500}
        />
        <Text style={[styles.fileText, !!value && styles.fileTextChosen]} numberOfLines={1}>
          {busy ? 'Opening…' : value || 'Choose a file'}
        </Text>
      </Pressable>
      {error ? (
        <Text style={styles.error}>{error}</Text>
      ) : limits ? (
        <Text style={styles.hint}>{limits}</Text>
      ) : null}
    </View>
  );
}

const mimeFor = (extension: string): string => {
  const map: Record<string, string> = {
    pdf: 'application/pdf',
    jpg: 'image/jpeg',
    jpeg: 'image/jpeg',
    png: 'image/png',
    ppt: 'application/vnd.ms-powerpoint',
    pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    doc: 'application/msword',
    docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  };
  return map[extension.toLowerCase()] ?? '*/*';
};

const styles = StyleSheet.create({
  stack: { gap: spacing.lg },
  section: { gap: spacing.md },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  sectionTitle: { flex: 1, fontSize: font.md, fontWeight: '700', color: colors.ink900 },
  sectionDescription: { fontSize: font.sm, color: colors.ink500, marginTop: -6 },
  fields: { gap: spacing.lg },
  textarea: { minHeight: 96, textAlignVertical: 'top' },

  entry: {
    gap: spacing.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.page,
  },
  entryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  entryTitle: { flex: 1, fontSize: font.sm, fontWeight: '700', color: colors.ink700 },
  sectionError: { fontSize: font.sm, color: colors.danger500, fontWeight: '500' },
  addEntry: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: spacing.sm,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: colors.brand600,
    borderRadius: radius.md,
  },
  addEntryText: { fontSize: font.sm, fontWeight: '600', color: colors.brand600 },

  fileField: { gap: 6 },
  fileLabel: { fontSize: font.sm, fontWeight: '600', color: colors.ink700 },
  required: { color: colors.danger500 },
  fileBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: 13,
    backgroundColor: colors.ink50,
  },
  fileBoxInvalid: { borderColor: colors.danger500 },
  fileText: { flex: 1, fontSize: font.sm, color: colors.ink500 },
  fileTextChosen: { color: colors.ink900, fontWeight: '500' },
  error: { fontSize: font.xs, color: colors.danger700, fontWeight: '500' },
  hint: { fontSize: font.xs, color: colors.ink500 },
});

// training-portal/src/app/shared/components/dynamic-form.component.ts
import { NgTemplateOutlet } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, effect, inject, input, output, signal } from '@angular/core';
import {
  AbstractControl,
  FormArray,
  FormBuilder,
  FormControl,
  FormGroup,
  ReactiveFormsModule,
  ValidatorFn,
  Validators,
} from '@angular/forms';
import { FieldType, RegistrationField, RegistrationForm, RegistrationSection } from '../../core/models';
import { FORMAT_MESSAGES, FORMAT_PATTERNS } from '../../core/validation/formats';
import { IconComponent } from './icon.component';

type FieldValue = string | string[] | number | boolean | null;

/** One filling of a repeating section: the same fields, answered again. */
type EntryValues = Record<string, FieldValue>;

/** Field types whose format is fixed by law; reused from the shared registry. */
const PATTERNS: Partial<Record<FieldType, RegExp>> = {
  email: new RegExp(FORMAT_PATTERNS.email),
  mobile: new RegExp(FORMAT_PATTERNS.mobile),
  pan: new RegExp(FORMAT_PATTERNS.pan),
  tan: new RegExp(FORMAT_PATTERNS.tan),
  gstin: new RegExp(FORMAT_PATTERNS.gstin),
  ifsc: new RegExp(FORMAT_PATTERNS.ifsc),
  pincode: new RegExp(FORMAT_PATTERNS.pincode),
  aadhaar: new RegExp(FORMAT_PATTERNS.aadhaar),
};

const FORMAT_HINTS: Partial<Record<FieldType, string>> = {
  email: FORMAT_MESSAGES.email,
  mobile: FORMAT_MESSAGES.mobile,
  pan: FORMAT_MESSAGES.pan,
  tan: FORMAT_MESSAGES.tan,
  gstin: FORMAT_MESSAGES.gstin,
  ifsc: FORMAT_MESSAGES.ifsc,
  pincode: FORMAT_MESSAGES.pincode,
  aadhaar: FORMAT_MESSAGES.aadhaar,
};

const UPPERCASE_TYPES: FieldType[] = ['pan', 'tan', 'gstin', 'ifsc'];

/**
 * Renders a Super Admin defined registration form. Used for the form-builder
 * preview, and in read-only mode to display an applicant's submitted answers
 * on the scrutiny screen.
 *
 * A section marked as repeating is held as a form array of identical groups —
 * one per entry — under the section's own key, which is how the API stores it
 * too. Every other section contributes its fields straight to the top level,
 * exactly as it always has. Fields are bound by control rather than by name so
 * the same markup can render a top-level field and a field inside an entry.
 */
@Component({
  selector: 'app-dynamic-form',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ReactiveFormsModule, IconComponent, NgTemplateOutlet],
  template: `
    <form [formGroup]="form()" (ngSubmit)="submitted.emit(form().getRawValue())" class="stack stack-lg">
      @for (section of enabledSections(); track section.id) {
        <section class="card">
          <div class="card__header">
            <div class="stack stack-xs">
              <span class="card__title">{{ section.title }}</span>
              @if (section.description) {
                <span class="card__subtitle">{{ section.description }}</span>
              }
            </div>
            @if (section.isRepeatable) {
              <span class="chip">{{ entriesOf(section).length }} of {{ maxEntries(section) }}</span>
            } @else {
              <span class="chip">{{ enabledFields(section).length }} fields</span>
            }
          </div>

          <div class="card__body">
            @if (!section.isRepeatable) {
              <div class="form-grid">
                @for (field of enabledFields(section); track field.key) {
                  <ng-container
                    *ngTemplateOutlet="fieldTpl; context: { field: field, group: form() }"
                  />
                }
              </div>
            } @else {
              <div class="stack stack-md">
                @for (entry of entriesOf(section); track $index) {
                  <div class="entry">
                    <div class="entry__head">
                      <span class="entry__title">{{ entryNoun(section) }} {{ $index + 1 }}</span>
                      @if (canRemove(section)) {
                        <button
                          type="button"
                          class="btn btn--icon is-danger"
                          [title]="'Remove ' + entryNoun(section).toLowerCase()"
                          (click)="removeEntry(section, $index)"
                        >
                          <app-icon name="trash" [size]="15" />
                        </button>
                      }
                    </div>
                    <div class="form-grid">
                      @for (field of enabledFields(section); track field.key) {
                        <ng-container
                          *ngTemplateOutlet="fieldTpl; context: { field: field, group: entry }"
                        />
                      }
                    </div>
                  </div>
                }

                @if (entriesOf(section).length === 0) {
                  <p class="text-muted text-sm">
                    No {{ entryNoun(section).toLowerCase() }} was added.
                  </p>
                }

                @if (canAdd(section)) {
                  <div>
                    <button type="button" class="btn btn--secondary btn--sm" (click)="addEntry(section)">
                      <app-icon name="plus" [size]="15" />
                      Add {{ entryNoun(section).toLowerCase() }}
                    </button>
                    <span class="field-hint" style="margin-left: 0.5rem">
                      Up to {{ maxEntries(section) }}.
                    </span>
                  </div>
                }
              </div>
            }
          </div>
        </section>
      }

      @if (!readonly()) {
        <div class="btn-row btn-row--end">
          <button type="submit" class="btn btn--primary">
            <app-icon name="send" [size]="15" /> Submit application
          </button>
        </div>
      }
    </form>

    <!-- One field, bound to whichever group it belongs to: the form itself, or
         one entry of a repeating section. -->
    <ng-template #fieldTpl let-field="field" let-group="group">
      @if (isVisible(field, group)) {
        <div class="field" [class.field--span-2]="field.colSpan === 2">
          <label class="field-label" [for]="idFor(field, group)">
            {{ field.label }}
            @if (field.validation.required) { <span class="req">*</span> }
          </label>

          @switch (field.type) {
            @case ('textarea') {
              <textarea
                class="textarea"
                [id]="idFor(field, group)"
                [formControl]="ctrl(group, field.key)"
                [placeholder]="field.placeholder || ''"
                [class.is-invalid]="invalid(group, field.key)"
              ></textarea>
            }
            @case ('select') {
              <select
                class="select"
                [id]="idFor(field, group)"
                [formControl]="ctrl(group, field.key)"
                [class.is-invalid]="invalid(group, field.key)"
              >
                <option value="">Select</option>
                @for (opt of field.options; track opt.value) {
                  <option [value]="opt.value">{{ opt.label }}</option>
                }
              </select>
            }
            @case ('multiselect') {
              <div class="check-grid">
                @for (opt of field.options; track opt.value) {
                  <label class="check">
                    <input
                      type="checkbox"
                      [checked]="isChecked(group, field.key, opt.value)"
                      [disabled]="readonly()"
                      (change)="toggleMulti(group, field.key, opt.value, $event)"
                    />
                    <span>{{ opt.label }}</span>
                  </label>
                }
              </div>
            }
            @case ('radio') {
              <div class="check-grid">
                @for (opt of field.options; track opt.value) {
                  <label class="check">
                    <input type="radio" [value]="opt.value" [formControl]="ctrl(group, field.key)" />
                    <span>{{ opt.label }}</span>
                  </label>
                }
              </div>
            }
            @case ('checkbox') {
              <label class="check">
                <input type="checkbox" [formControl]="ctrl(group, field.key)" />
                <span class="text-sm">{{ field.helpText || 'Yes' }}</span>
              </label>
            }
            @case ('file') {
              <div class="file-box">
                <app-icon name="upload" [size]="16" />
                <span class="text-sm">
                  {{ readonly() ? (value(group, field.key) || 'Not uploaded') : 'Choose a file' }}
                </span>
                @if (!readonly()) {
                  <input type="file" [id]="idFor(field, group)" (change)="onFile(group, field.key, $event)" />
                }
              </div>
            }
            @case ('date') {
              <input
                type="date"
                class="input"
                [id]="idFor(field, group)"
                [formControl]="ctrl(group, field.key)"
                [class.is-invalid]="invalid(group, field.key)"
              />
            }
            @case ('number') {
              <input
                type="number"
                class="input"
                [id]="idFor(field, group)"
                [formControl]="ctrl(group, field.key)"
                [placeholder]="field.placeholder || ''"
                [class.is-invalid]="invalid(group, field.key)"
              />
            }
            @default {
              <input
                type="text"
                class="input"
                [id]="idFor(field, group)"
                [formControl]="ctrl(group, field.key)"
                [placeholder]="field.placeholder || ''"
                [class.is-invalid]="invalid(group, field.key)"
                [attr.maxlength]="maxLengthFor(field)"
                [style.text-transform]="isUppercase(field) ? 'uppercase' : null"
              />
            }
          }

          @if (hintFor(field)) {
            <span class="field-hint">{{ hintFor(field) }}</span>
          }
          @if (invalid(group, field.key)) {
            <span class="field-error">{{ errorFor(group, field) }}</span>
          }
        </div>
      }
    </ng-template>
  `,
  styles: [
    `
      .file-box {
        position: relative;
        display: flex;
        align-items: center;
        gap: 0.5rem;
        padding: 0.55rem 0.7rem;
        border: 1px dashed var(--border-strong);
        border-radius: var(--radius);
        color: var(--ink-500);
        background: var(--surface-muted);
      }
      .file-box input[type='file'] {
        position: absolute;
        inset: 0;
        opacity: 0;
        cursor: pointer;
      }
      .entry {
        border: 1px solid var(--border);
        border-radius: var(--radius);
        padding: 0.85rem;
        background: var(--surface-muted);
      }
      .entry__head {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 0.5rem;
        margin-bottom: 0.6rem;
      }
      .entry__title {
        font-size: var(--fs-sm);
        font-weight: 600;
        color: var(--ink-700);
      }
    `,
  ],
})
export class DynamicFormComponent {
  private readonly fb = inject(FormBuilder);

  readonly definition = input.required<RegistrationForm>();
  readonly values = input<Record<string, FieldValue | EntryValues[]>>({});
  readonly readonly = input(false);

  /**
   * Shows the form as an applicant would meet it rather than as it was
   * answered: a repeating section still starts with its opening entries, so a
   * preview of a form nobody has filled in is not an empty card. Off on the
   * scrutiny screen, where an empty section means exactly that.
   */
  readonly preview = input(false);
  readonly submitted = output<Record<string, unknown>>();

  private readonly formSignal = signal<FormGroup>(this.fb.group({}));
  readonly form = computed(() => this.formSignal());

  constructor() {
    effect(() => {
      const definition = this.definition();
      const values = this.values();
      const group: Record<string, AbstractControl> = {};

      for (const section of definition.sections) {
        if (section.isEnabled === false) continue;
        const fields = this.enabledFields(section);

        if (!section.isRepeatable) {
          for (const field of fields) {
            group[field.key] = this.controlFor(field, values[field.key] as FieldValue);
          }
          continue;
        }

        const raw = values[this.keyOf(section)];
        const answered = Array.isArray(raw) ? (raw as EntryValues[]) : [];

        /* Read-only shows exactly what was answered. While filling, the
           smallest allowed number of entries is on screen from the start, so
           a required section is never an empty card with a button. */
        const shown = this.readonly() && !this.preview()
          ? answered.length
          : Math.max(answered.length, this.minEntries(section), 1);

        group[this.keyOf(section)] = this.fb.array(
          Array.from({ length: shown }, (_, index) =>
            this.entryGroup(fields, answered[index] ?? {}),
          ),
        );
      }

      this.formSignal.set(this.fb.group(group));
    });
  }

  /* --------------------------------------------------------- definition */

  /** Disabled sections and fields never render and never validate. */
  protected readonly enabledSections = computed(() =>
    this.definition().sections.filter((s) => s.isEnabled !== false),
  );

  protected enabledFields(section: { fields: RegistrationField[] }): RegistrationField[] {
    return section.fields.filter((f) => f.isEnabled !== false);
  }

  /** What one entry is called, falling back to the section's own title. */
  protected entryNoun(section: RegistrationSection): string {
    return section.itemLabel?.trim() || section.title;
  }

  protected minEntries(section: RegistrationSection): number {
    return Math.max(0, section.minEntries ?? 1);
  }

  protected maxEntries(section: RegistrationSection): number {
    return Math.max(1, section.maxEntries ?? 10);
  }

  /**
   * The key a repeating section's entries live under. Falls back to the id so
   * a form saved before section keys existed still renders.
   */
  private keyOf(section: RegistrationSection): string {
    return section.key?.trim() || `section${section.id}`;
  }

  /* -------------------------------------------------------------- entries */

  protected entriesOf(section: RegistrationSection): FormGroup[] {
    const array = this.form().get(this.keyOf(section));
    return array instanceof FormArray ? (array.controls as FormGroup[]) : [];
  }

  protected canAdd(section: RegistrationSection): boolean {
    return !this.readonly() && this.entriesOf(section).length < this.maxEntries(section);
  }

  protected canRemove(section: RegistrationSection): boolean {
    return (
      !this.readonly() &&
      this.entriesOf(section).length > Math.max(this.minEntries(section), 1)
    );
  }

  protected addEntry(section: RegistrationSection): void {
    const array = this.form().get(this.keyOf(section));
    if (!(array instanceof FormArray) || !this.canAdd(section)) return;
    array.push(this.entryGroup(this.enabledFields(section), {}));
  }

  protected removeEntry(section: RegistrationSection, index: number): void {
    const array = this.form().get(this.keyOf(section));
    if (!(array instanceof FormArray) || !this.canRemove(section)) return;
    array.removeAt(index);
  }

  private entryGroup(fields: RegistrationField[], values: EntryValues): FormGroup {
    const group: Record<string, FormControl> = {};
    for (const field of fields) group[field.key] = this.controlFor(field, values[field.key]);
    return this.fb.group(group);
  }

  private controlFor(field: RegistrationField, value: FieldValue | undefined): FormControl {
    return new FormControl<FieldValue>(
      { value: value ?? defaultFor(field), disabled: this.readonly() },
      { validators: validatorsFor(field) },
    );
  }

  /* --------------------------------------------------------------- fields */

  /** The control a field is bound to within the group it was rendered in. */
  protected ctrl(group: FormGroup, key: string): FormControl {
    return group.get(key) as FormControl;
  }

  /**
   * Unique per entry, so clicking a label focuses the field in the entry it
   * was clicked in rather than the first one on the page.
   */
  protected idFor(field: RegistrationField, group: FormGroup): string {
    const parent = group.parent;
    if (parent instanceof FormArray) {
      return `${field.key}-${parent.controls.indexOf(group)}`;
    }
    return field.key;
  }

  /**
   * A conditional field reads its trigger from the group it lives in, so each
   * entry answers for itself, and from the form when the trigger is a field
   * outside the section.
   */
  protected isVisible(field: RegistrationField, group: FormGroup): boolean {
    if (!field.visibleWhenFieldKey) return true;
    const source = group.get(field.visibleWhenFieldKey)
      ?? this.form().get(field.visibleWhenFieldKey);
    const raw = source?.value;
    const current = typeof raw === 'boolean' ? String(raw) : String(raw ?? '');
    return (field.visibleWhenValues ?? []).includes(current);
  }

  protected value(group: FormGroup, key: string): string {
    const raw = group.get(key)?.value;
    if (raw === null || raw === undefined || raw === '') return '';
    if (Array.isArray(raw)) return raw.join(', ');
    if (typeof raw === 'boolean') return raw ? 'Yes' : 'No';
    return String(raw);
  }

  protected invalid(group: FormGroup, key: string): boolean {
    const control = group.get(key);
    return !!control && control.invalid && (control.dirty || control.touched);
  }

  protected isUppercase(field: RegistrationField): boolean {
    return UPPERCASE_TYPES.includes(field.type);
  }

  protected maxLengthFor(field: RegistrationField): number | null {
    if (field.type === 'pan' || field.type === 'tan') return 10;
    if (field.type === 'gstin') return 15;
    if (field.type === 'ifsc') return 11;
    if (field.type === 'aadhaar') return 12;
    if (field.type === 'pincode') return 6;
    return field.validation.maxLength ?? null;
  }

  protected hintFor(field: RegistrationField): string {
    if (field.type === 'checkbox') return '';
    return field.helpText || FORMAT_HINTS[field.type] || '';
  }

  protected errorFor(group: FormGroup, field: RegistrationField): string {
    const errors = group.get(field.key)?.errors ?? {};
    if (errors['required']) return `${field.label} is required.`;
    if (errors['pattern']) {
      return FORMAT_HINTS[field.type] ?? `Enter a valid ${field.label.toLowerCase()}.`;
    }
    if (errors['minlength']) return `Minimum ${field.validation.minLength} characters.`;
    if (errors['maxlength']) return `Maximum ${field.validation.maxLength} characters.`;
    if (errors['min']) return `Minimum value is ${field.validation.min}.`;
    if (errors['max']) return `Maximum value is ${field.validation.max}.`;
    return 'Invalid value.';
  }

  protected isChecked(group: FormGroup, key: string, option: string): boolean {
    const raw = group.get(key)?.value;
    return Array.isArray(raw) && raw.includes(option);
  }

  protected toggleMulti(group: FormGroup, key: string, option: string, event: Event): void {
    const control = group.get(key);
    if (!control) return;
    const checked = (event.target as HTMLInputElement).checked;
    const current = Array.isArray(control.value) ? [...(control.value as string[])] : [];
    const next = checked ? [...current, option] : current.filter((v) => v !== option);
    control.setValue(next);
    control.markAsDirty();
  }

  protected onFile(group: FormGroup, key: string, event: Event): void {
    const file = (event.target as HTMLInputElement).files?.[0];
    const control = group.get(key);
    control?.setValue(file ? file.name : null);
    control?.markAsDirty();
  }
}

function defaultFor(field: RegistrationField): FieldValue {
  if (field.type === 'multiselect') return [];
  if (field.type === 'checkbox') return false;
  return '';
}

function validatorsFor(field: RegistrationField): ValidatorFn[] {
  const rules: ValidatorFn[] = [];
  const v = field.validation;
  if (v.required) {
    rules.push(field.type === 'checkbox' ? Validators.requiredTrue : Validators.required);
  }
  if (v.minLength) rules.push(Validators.minLength(v.minLength));
  if (v.maxLength) rules.push(Validators.maxLength(v.maxLength));
  if (v.min !== null && v.min !== undefined) rules.push(Validators.min(v.min));
  if (v.max !== null && v.max !== undefined) rules.push(Validators.max(v.max));
  const pattern = v.pattern ? new RegExp(v.pattern) : PATTERNS[field.type];
  if (pattern) rules.push(Validators.pattern(pattern));
  return rules;
}
