// mobile-coordinator/app/workshop/[id]/marksheet.tsx
import { Ionicons } from '@expo/vector-icons';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { ApiError } from '../../../src/api/client';
import { marksheet as marksheetApi } from '../../../src/api/endpoints';
import type { Marksheet, MarksheetRow, MarksheetRowSave } from '../../../src/api/types';
import { Banner, Button, Card, EmptyState, Field, Loading, StatusPill } from '../../../src/components/ui';
import { Picker } from '../../../src/components/Picker';
import { colors, radius, spacing } from '../../../src/theme';
import { useWorkshop } from '../../../src/workshop/WorkshopContext';

/**
 * The trainer's marksheet, one candidate at a time.
 *
 * A viva is marked candidate by candidate, not as a grid, so the phone shows
 * the list and opens one sheet at a time — the same order the trainer works in,
 * with the skills in the order they were set up.
 *
 * No result is decided here. The marks go to the server, which works the result
 * out and sends the sheet back, so this screen and the portal can never
 * disagree about who passed. Offline the marks are queued like everything else
 * and the results catch up when the queue drains.
 */
export default function MarksheetScreen() {
  const { id } = useWorkshop();

  const [sheet, setSheet] = useState<Marksheet | null>(null);
  const [loading, setLoading] = useState(true);
  const [failure, setFailure] = useState<string | null>(null);
  const [openFor, setOpenFor] = useState<number | null>(null);

  const load = useCallback(async () => {
    setFailure(null);
    try {
      setSheet(await marksheetApi.get(id));
    } catch (caught) {
      setFailure(caught instanceof ApiError ? caught.message : 'Could not load the marksheet.');
    } finally {
      setLoading(false);
    }
  }, [id]);

  useEffect(() => {
    void load();
  }, [load]);

  if (loading && !sheet) return <Loading label="Loading the marksheet…" />;

  if (!sheet) {
    return (
      <EmptyState
        title="Marksheet unavailable"
        message={failure ?? 'Open this screen once with a signal and it will be there offline.'}
      />
    );
  }

  if (sheet.evaluation.kind === 'None') {
    return (
      <EmptyState
        title="Nothing to mark"
        message={`${sheet.programTypeName} has no examination, so there is no marksheet for it.`}
      />
    );
  }

  if (sheet.rows.length === 0) {
    return (
      <EmptyState
        title="Nobody enrolled"
        message="This programme has no enrolled candidates to mark."
      />
    );
  }

  const scheme = sheet.evaluation;
  const editing = sheet.rows.find((row) => row.participantId === openFor) ?? null;

  return (
    <>
      <ScrollView contentContainerStyle={styles.content}>
        {failure ? <Banner tone="danger">{failure}</Banner> : null}
        {sheet.readOnlyReason ? <Banner tone="info">{sheet.readOnlyReason}</Banner> : null}

        {scheme.hasViva && sheet.skills.length === 0 ? (
          <Banner tone="warning">
            The viva has no skills set up yet, so it cannot be marked. They are added in the portal,
            under the program type.
          </Banner>
        ) : null}

        <Card style={styles.summary}>
          <Text style={styles.summaryTitle}>{scheme.kindLabel}</Text>
          <Text style={styles.summaryText}>{pattern(sheet)}</Text>
          <Text style={styles.summaryCount}>
            {sheet.markedCount} of {sheet.rows.length} decided · {sheet.passCount} passed ·{' '}
            {sheet.failCount} did not qualify
          </Text>
        </Card>

        {sheet.rows.map((row) => (
          <Pressable
            key={row.participantId}
            style={styles.row}
            disabled={!sheet.canEdit || row.isLocked}
            onPress={() => setOpenFor(row.participantId)}
          >
            <View style={styles.rowText}>
              <Text style={styles.rowName}>{row.name}</Text>
              <Text style={styles.rowMeta}>
                {row.applicationNo}
                {row.total != null ? ` · ${row.total} of ${scheme.totalMarks}` : ' · not marked'}
              </Text>
              {row.isLocked ? (
                <Text style={styles.rowNote}>Certificate issued — marks locked</Text>
              ) : row.pending ? (
                <Text style={styles.rowNote}>{row.pending}</Text>
              ) : row.shortfall ? (
                <Text style={styles.rowNote}>{row.shortfall}</Text>
              ) : null}
            </View>
            <StatusPill value={row.result} />
            {sheet.canEdit && !row.isLocked ? (
              <Ionicons name="chevron-forward" size={18} color={colors.ink400} />
            ) : null}
          </Pressable>
        ))}
      </ScrollView>

      <Modal
        visible={editing !== null}
        animationType="slide"
        onRequestClose={() => setOpenFor(null)}
      >
        {editing ? (
          <CandidateSheet
            programmeId={id}
            sheet={sheet}
            row={editing}
            onClose={() => setOpenFor(null)}
            onSaved={(saved) => {
              setSheet(saved);
              setOpenFor(null);
            }}
          />
        ) : null}
      </Modal>
    </>
  );
}

/* --------------------------------------------------------- one candidate */

function CandidateSheet({
  programmeId,
  sheet,
  row,
  onClose,
  onSaved,
}: {
  programmeId: number;
  sheet: Marksheet;
  row: MarksheetRow;
  onClose: () => void;
  onSaved: (saved: Marksheet) => void;
}) {
  const scheme = sheet.evaluation;

  /* Seeded from what is recorded, so a correction starts from the mark that is
     being corrected rather than from blank. */
  const [written, setWritten] = useState(text(row.writtenMarks));
  const [skills, setSkills] = useState<Record<number, string>>(() =>
    Object.fromEntries(row.skillMarks.map((mark) => [mark.skillId, String(mark.marks)])),
  );
  const [trainerId, setTrainerId] = useState<number | null>(
    row.skillMarks.find((mark) => mark.trainerId)?.trainerId ?? null,
  );
  const [busy, setBusy] = useState(false);
  const [failure, setFailure] = useState<string | null>(null);

  const problem = useMemo(() => {
    if (scheme.hasWritten && written !== '' && !within(written, scheme.writtenMarks)) {
      return `The written paper is marked out of ${scheme.writtenMarks}.`;
    }
    for (const skill of sheet.skills) {
      const value = skills[skill.id];
      if (value !== undefined && value !== '' && !within(value, skill.maxMarks)) {
        return `'${skill.name}' is marked out of ${skill.maxMarks}.`;
      }
    }
    return null;
  }, [written, skills, scheme, sheet.skills]);

  const vivaTotal = sheet.skills.reduce((sum, skill) => {
    const value = Number(skills[skill.id]);
    return Number.isFinite(value) && skills[skill.id] !== '' && skills[skill.id] !== undefined
      ? sum + value
      : sum;
  }, 0);

  const save = async () => {
    if (problem) return;
    setBusy(true);
    setFailure(null);

    const payload: MarksheetRowSave = {
      participantId: row.participantId,
      trainerId,
      /* Only sent when this program type has one: a sheet that never showed
         the written box must not wipe a mark it did not display. */
      /* Never sent when the paper decided it: the server refuses a typed-over
         exam score, and offering it here would only queue a refusal. */
      ...(scheme.hasWritten && !row.writtenFromExam
        ? { writtenMarks: written === '' ? null : Number(written) }
        : {}),
      skillMarks: sheet.skills
        .filter((skill) => !skill.isRetired && skills[skill.id] !== undefined)
        .map((skill) => ({
          skillId: skill.id,
          marks: skills[skill.id] === '' ? 0 : Number(skills[skill.id]),
          /* An emptied box takes the mark back rather than recording a zero. */
          clear: skills[skill.id] === '',
        })),
    };

    try {
      /* What the sheet will look like, used as the answer when the request is
         queued: the coordinator sees the marks they just entered either way,
         and only the result waits for the server. */
      const optimistic = applyLocally(sheet, payload);
      onSaved(await marksheetApi.save(programmeId, [payload], optimistic));
    } catch (caught) {
      setFailure(caught instanceof ApiError ? caught.message : 'Could not save these marks.');
      setBusy(false);
    }
  };

  return (
    <ScrollView contentContainerStyle={styles.sheet}>
      <View style={styles.sheetHead}>
        <View style={styles.rowText}>
          <Text style={styles.sheetName}>{row.name}</Text>
          <Text style={styles.rowMeta}>{row.applicationNo}</Text>
        </View>
        <Pressable onPress={onClose} hitSlop={10}>
          <Ionicons name="close" size={24} color={colors.ink500} />
        </Pressable>
      </View>

      {sheet.trainers.length > 0 ? (
        <Picker
          label="Marked by"
          placeholder="Not recorded"
          value={trainerId === null ? null : String(trainerId)}
          options={sheet.trainers.map((trainer) => ({
            value: String(trainer.id),
            label: trainer.fullName,
          }))}
          onChange={(value) => setTrainerId(Number(value))}
        />
      ) : null}

      {scheme.hasWritten ? (
        <Field
          label="Written examination"
          keyboardType="number-pad"
          editable={!row.writtenFromExam}
          value={written}
          onChangeText={setWritten}
          hint={
            row.writtenFromExam
              ? `From the paper sat online — ${row.examPercentage}% on the best of ` +
                `${row.examAttempts} attempt${row.examAttempts === 1 ? '' : 's'}.`
              : `Out of ${scheme.writtenMarks}. Leave blank if the paper is not marked yet.`
          }
        />
      ) : null}

      {scheme.hasViva
        ? sheet.skills.map((skill) => (
            <Field
              key={skill.id}
              label={skill.name}
              keyboardType="number-pad"
              editable={!skill.isRetired}
              value={skills[skill.id] ?? ''}
              onChangeText={(value) => setSkills((prev) => ({ ...prev, [skill.id]: value }))}
              hint={
                skill.isRetired
                  ? 'Retired — kept for the marks already given.'
                  : skill.description
                    ? `Out of ${skill.maxMarks}. ${skill.description}`
                    : `Out of ${skill.maxMarks}.`
              }
            />
          ))
        : null}

      {scheme.hasViva ? (
        <View style={styles.tally}>
          <Text style={styles.tallyText}>
            Viva {vivaTotal} of {scheme.vivaMarks}
          </Text>
          <Text style={styles.tallyMeta}>
            {scheme.vivaPassMarks} needed to clear this section
          </Text>
        </View>
      ) : null}

      {problem ? <Banner tone="danger">{problem}</Banner> : null}
      {failure ? <Banner tone="danger">{failure}</Banner> : null}

      <Button label="Save marks" onPress={save} loading={busy} disabled={!!problem} />
      <Button label="Cancel" variant="ghost" onPress={onClose} />
    </ScrollView>
  );
}

/* ------------------------------------------------------------------ bits */

const text = (value?: number | null) => (value === null || value === undefined ? '' : String(value));

const within = (value: string, max: number) => {
  const parsed = Number(value);
  return Number.isFinite(parsed) && parsed >= 0 && parsed <= max;
};

function pattern(sheet: Marksheet): string {
  const scheme = sheet.evaluation;
  const parts: string[] = [];
  if (scheme.hasWritten) {
    parts.push(`written ${scheme.writtenMarks} (pass ${scheme.writtenPassMarks})`);
  }
  if (scheme.hasViva) parts.push(`viva ${scheme.vivaMarks} (pass ${scheme.vivaPassMarks})`);
  return (
    `Out of ${scheme.totalMarks}: ${parts.join(', ')}. ` +
    `${scheme.overallPassMarks} needed overall.`
  );
}

/**
 * The sheet as it will read once these marks are in.
 *
 * Used only as the stand-in answer while the write is queued, so the result and
 * the counts are left exactly as the server last reported them — a mark that
 * has not reached the server has not decided anything.
 */
function applyLocally(sheet: Marksheet, row: MarksheetRowSave): Marksheet {
  return {
    ...sheet,
    rows: sheet.rows.map((existing) => {
      if (existing.participantId !== row.participantId) return existing;

      const kept = existing.skillMarks.filter(
        (mark) => !row.skillMarks.some((sent) => sent.skillId === mark.skillId),
      );
      const added = row.skillMarks
        .filter((sent) => !sent.clear)
        .map((sent) => ({
          skillId: sent.skillId,
          marks: sent.marks,
          trainerId: row.trainerId ?? null,
          trainerName: sheet.trainers.find((t) => t.id === row.trainerId)?.fullName ?? null,
          markedOn: new Date().toISOString(),
        }));

      const skillMarks = [...kept, ...added];
      const viva = skillMarks.length > 0 ? skillMarks.reduce((sum, m) => sum + m.marks, 0) : null;
      const written =
        'writtenMarks' in row ? (row.writtenMarks ?? null) : (existing.writtenMarks ?? null);

      return { ...existing, skillMarks, vivaMarks: viva, writtenMarks: written };
    }),
  };
}

const styles = StyleSheet.create({
  content: { padding: spacing.lg, gap: spacing.md, paddingBottom: spacing.xxl },
  summary: { gap: 4 },
  summaryTitle: { fontSize: 14, fontWeight: '700', color: colors.ink900 },
  summaryText: { fontSize: 12, color: colors.ink600 },
  summaryCount: { fontSize: 12, color: colors.ink500, marginTop: 2 },
  row: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: radius.md,
    flexDirection: 'row',
    gap: spacing.md,
    padding: spacing.md,
  },
  rowText: { flex: 1, gap: 2 },
  rowName: { fontSize: 14, fontWeight: '600', color: colors.ink900 },
  rowMeta: { fontSize: 12, color: colors.ink500 },
  rowNote: { fontSize: 11, color: colors.ink400 },
  sheet: {
    backgroundColor: colors.page,
    gap: spacing.md,
    padding: spacing.lg,
    paddingBottom: spacing.xxl,
    paddingTop: spacing.xl,
  },
  sheetHead: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.md },
  sheetName: { fontSize: 18, fontWeight: '700', color: colors.ink900 },
  tally: {
    backgroundColor: colors.blush,
    borderRadius: radius.md,
    gap: 2,
    padding: spacing.md,
  },
  tallyText: { fontSize: 14, fontWeight: '700', color: colors.brand700 },
  tallyMeta: { fontSize: 12, color: colors.ink600 },
});

// training-portal/src/app/features/operations/marksheet.component.ts
import { ChangeDetectionStrategy, Component, computed, effect, inject, input, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Id, Marksheet, MarksheetRow, MarksheetRowSave } from '../../core/models';
import { MarksheetService } from '../../core/services/marksheet.service';
import { ToastService } from '../../core/services/toast.service';
import { IconComponent } from '../../shared/components/icon.component';
import { StatusBadgeComponent } from '../../shared/components/status-badge.component';

/** An edit in progress: what is typed, before it has been sent. */
interface Draft {
  written?: number | null;
  skills: Record<number, number | null>;
}

/**
 * The trainer's marksheet for one programme.
 *
 * Laid out the way it is marked — one line per candidate, one column per skill
 * — and saved as a pass rather than a field at a time, because that is how the
 * marking happens: down the list with the trainer, then filed.
 *
 * Nothing here decides a result. The totals shown while typing are a preview;
 * the result is whatever the server says when the marks land, so the portal and
 * the coordinator's app can never disagree about who passed.
 */
@Component({
  selector: 'app-marksheet',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [FormsModule, IconComponent, StatusBadgeComponent],
  template: `
    @if (sheet(); as data) {
      <div class="card__body stack stack-md">
        <div class="head">
          <div class="stack stack-xs">
            <strong class="text-sm">{{ data.evaluation.kindLabel }}</strong>
            <span class="text-xs text-muted">{{ pattern() }}</span>
          </div>

          <div class="btn-row btn-row--end">
            @if (data.trainers.length > 0 && data.canEdit) {
              <label class="marked-by">
                <span class="text-xs text-muted">Marked by</span>
                <select class="select select--sm" [(ngModel)]="trainerId">
                  <option [ngValue]="null">Not recorded</option>
                  @for (trainer of data.trainers; track trainer.id) {
                    <option [ngValue]="trainer.id">{{ trainer.fullName }}</option>
                  }
                </select>
              </label>
            }
            @if (data.canEdit) {
              <button
                type="button"
                class="btn btn--ghost"
                [disabled]="dirtyCount() === 0 || saving()"
                (click)="discard()"
              >
                Discard
              </button>
              <button
                type="button"
                class="btn btn--primary"
                [disabled]="dirtyCount() === 0 || saving()"
                (click)="save()"
              >
                @if (saving()) { <span class="spinner"></span> }
                Save {{ dirtyCount() }} candidate{{ dirtyCount() === 1 ? '' : 's' }}
              </button>
            }
          </div>
        </div>

        <span class="text-xs text-muted">
          {{ data.markedCount }} of {{ data.rows.length }} decided · {{ data.passCount }} passed ·
          {{ data.failCount }} did not qualify
          @if (satOnline() > 0) {
            · {{ satOnline() }} sat the paper online
          }
        </span>

        @if (data.readOnlyReason) {
          <div class="alert alert--info">
            <app-icon name="info" [size]="16" />
            <span>{{ data.readOnlyReason }}</span>
          </div>
        }

        @if (data.evaluation.kind === 'None') {
          <div class="alert alert--info">
            <app-icon name="info" [size]="16" />
            <span>
              {{ data.programTypeName }} has no examination, so there is nothing to mark.
            </span>
          </div>
        } @else if (data.evaluation.hasViva && data.skills.length === 0) {
          <div class="alert alert--warning">
            <app-icon name="alert" [size]="16" />
            <span>
              The viva has no skills set up yet, so it cannot be marked. Add them under
              Evaluation Skills for {{ data.programTypeName }}.
            </span>
          </div>
        }
      </div>

      @if (data.rows.length > 0 && data.evaluation.kind !== 'None') {
        <div class="table-wrap">
          <table class="table table--compact">
            <thead>
              <tr>
                <th class="sticky-col">Candidate</th>
                <th style="width: 90px" class="text-center">Attd.</th>
                @if (data.evaluation.hasWritten) {
                  <th style="width: 110px" class="text-center">
                    Written<div class="text-xs text-muted">of {{ data.evaluation.writtenMarks }}</div>
                  </th>
                }
                @for (skill of data.skills; track skill.id) {
                  <th style="width: 110px" class="text-center" [title]="skill.description || skill.name">
                    {{ skill.name }}
                    <div class="text-xs text-muted">
                      of {{ skill.maxMarks }}{{ skill.isRetired ? ' · retired' : '' }}
                    </div>
                  </th>
                }
                @if (data.evaluation.hasViva) {
                  <th style="width: 90px" class="text-center">
                    Viva<div class="text-xs text-muted">of {{ data.evaluation.vivaMarks }}</div>
                  </th>
                }
                <th style="width: 90px" class="text-center">
                  Total<div class="text-xs text-muted">of {{ data.evaluation.totalMarks }}</div>
                </th>
                <th style="width: 230px">Result</th>
              </tr>
            </thead>
            <tbody>
              @for (row of data.rows; track row.participantId) {
                <tr [class.is-dirty]="isDirty(row.participantId)">
                  <td class="cell-primary sticky-col">
                    {{ row.name }}
                    <div class="text-xs text-muted">{{ row.applicationNo }}</div>
                  </td>
                  <td class="text-center cell-muted tabular">{{ row.attendancePercent }}%</td>

                  @if (data.evaluation.hasWritten) {
                    <td class="text-center">
                      <input
                        class="input input--mark"
                        type="number"
                        min="0"
                        [max]="data.evaluation.writtenMarks"
                        [disabled]="!data.canEdit || row.isLocked || row.writtenFromExam"
                        [ngModel]="writtenOf(row)"
                        (ngModelChange)="setWritten(row, $event)"
                        [title]="row.writtenFromExam ? 'From the paper sat online' : ''"
                      />
                      @if (row.writtenFromExam) {
                        <div class="text-xs text-muted">
                          Online · {{ row.examPercentage }}%
                        </div>
                      }
                    </td>
                  }

                  @for (skill of data.skills; track skill.id) {
                    <td class="text-center">
                      <input
                        class="input input--mark"
                        type="number"
                        min="0"
                        [max]="skill.maxMarks"
                        [disabled]="!data.canEdit || row.isLocked || skill.isRetired"
                        [ngModel]="skillOf(row, skill.id)"
                        (ngModelChange)="setSkill(row, skill.id, $event)"
                      />
                    </td>
                  }

                  @if (data.evaluation.hasViva) {
                    <td class="text-center tabular">{{ vivaOf(row) ?? '—' }}</td>
                  }
                  <td class="text-center tabular"><strong>{{ totalOf(row) ?? '—' }}</strong></td>

                  <td>
                    @if (isDirty(row.participantId)) {
                      <span class="text-xs text-muted">Not saved yet</span>
                    } @else {
                      <app-status-badge [value]="row.result" />
                      @if (row.isLocked) {
                        <div class="text-xs text-muted">Certificate issued — marks locked</div>
                      } @else if (row.pending) {
                        <div class="text-xs text-muted">{{ row.pending }}</div>
                      } @else if (row.shortfall) {
                        <div class="text-xs text-muted">{{ row.shortfall }}</div>
                      }
                    }
                  </td>
                </tr>
              }
            </tbody>
          </table>
        </div>
      } @else if (data.rows.length === 0) {
        <div class="card__body">
          <span class="text-sm text-muted">Nobody is enrolled on this programme yet.</span>
        </div>
      }
    } @else {
      <div class="card__body"><span class="text-sm text-muted">Loading the marksheet…</span></div>
    }
  `,
  styles: [
    `
      .head {
        align-items: flex-start;
        display: flex;
        flex-wrap: wrap;
        gap: 0.75rem;
        justify-content: space-between;
      }
      .marked-by {
        align-items: center;
        display: flex;
        gap: 0.4rem;
      }
      .input--mark {
        max-width: 78px;
        padding: 0.3rem 0.4rem;
        text-align: center;
      }
      .sticky-col {
        background: inherit;
        left: 0;
        position: sticky;
        z-index: 1;
      }
      tbody tr.is-dirty {
        background: var(--warning-50, #fff8e6);
      }
    `,
  ],
})
export class MarksheetComponent {
  private readonly service = inject(MarksheetService);
  private readonly toast = inject(ToastService);

  readonly programmeId = input.required<Id>();

  protected readonly sheet = signal<Marksheet | null>(null);
  protected readonly saving = signal(false);

  /** Who is marking, applied to everything in this pass. */
  protected trainerId: Id | null = null;

  /** Edits not sent yet, by participant. */
  private readonly drafts = signal<Record<number, Draft>>({});

  protected readonly dirtyCount = computed(() => Object.keys(this.drafts()).length);

  constructor() {
    effect(() => {
      const id = this.programmeId();
      this.drafts.set({});
      this.service.get(id).subscribe((sheet) => this.sheet.set(sheet));
    });
  }

  /** The pattern in a sentence, so the columns explain themselves. */
  protected readonly pattern = computed(() => {
    const scheme = this.sheet()?.evaluation;
    if (!scheme || scheme.kind === 'None') return '';
    const parts: string[] = [];
    if (scheme.hasWritten) {
      parts.push(`written ${scheme.writtenMarks} (pass ${scheme.writtenPassMarks})`);
    }
    if (scheme.hasViva) parts.push(`viva ${scheme.vivaMarks} (pass ${scheme.vivaPassMarks})`);
    return `Out of ${scheme.totalMarks}: ${parts.join(', ')}. ` +
      `${scheme.overallPassMarks} needed overall.`;
  });

  /** How many written marks came from the online paper rather than a typist. */
  protected readonly satOnline = computed(
    () => this.sheet()?.rows.filter((row) => row.writtenFromExam).length ?? 0,
  );

  protected isDirty(participantId: Id): boolean {
    return this.drafts()[participantId] !== undefined;
  }

  /* ------------------------------------------------- what a cell shows ----
     The draft if there is one, otherwise what was saved. A cleared box is
     null, which is "not marked" — never a silent zero. */

  protected writtenOf(row: MarksheetRow): number | null {
    const draft = this.drafts()[row.participantId];
    return draft && 'written' in draft ? (draft.written ?? null) : (row.writtenMarks ?? null);
  }

  protected skillOf(row: MarksheetRow, skillId: Id): number | null {
    const draft = this.drafts()[row.participantId];
    if (draft && skillId in draft.skills) return draft.skills[skillId] ?? null;
    return row.skillMarks.find((m) => m.skillId === skillId)?.marks ?? null;
  }

  /** Added up as typed, so a trainer sees the total before saving. */
  protected vivaOf(row: MarksheetRow): number | null {
    const skills = this.sheet()?.skills ?? [];
    const marks = skills
      .map((skill) => this.skillOf(row, skill.id))
      .filter((mark): mark is number => mark !== null);
    return marks.length > 0 ? marks.reduce((sum, mark) => sum + mark, 0) : null;
  }

  protected totalOf(row: MarksheetRow): number | null {
    const scheme = this.sheet()?.evaluation;
    if (!scheme) return null;
    const written = scheme.hasWritten ? this.writtenOf(row) : 0;
    const viva = scheme.hasViva ? this.vivaOf(row) : 0;
    if (written === null || viva === null) return null;
    return written + viva;
  }

  /* --------------------------------------------------------- editing */

  protected setWritten(row: MarksheetRow, value: unknown): void {
    const marks = toMark(value);
    this.edit(row, (draft) => ({ ...draft, written: marks }));
  }

  protected setSkill(row: MarksheetRow, skillId: Id, value: unknown): void {
    const marks = toMark(value);
    this.edit(row, (draft) => ({ ...draft, skills: { ...draft.skills, [skillId]: marks } }));
  }

  private edit(row: MarksheetRow, change: (draft: Draft) => Draft): void {
    this.drafts.update((all) => {
      const current = all[row.participantId] ?? { skills: {} };
      return { ...all, [row.participantId]: change(current) };
    });
  }

  protected discard(): void {
    this.drafts.set({});
  }

  /* ----------------------------------------------------------- saving */

  protected save(): void {
    const sheet = this.sheet();
    const drafts = this.drafts();
    if (!sheet || Object.keys(drafts).length === 0) return;

    const rows: MarksheetRowSave[] = Object.entries(drafts).map(([id, draft]) => ({
      participantId: Number(id),
      /* Omitted unless it was touched: a sheet that never showed the written
         column must not send null and wipe it. */
      ...('written' in draft ? { writtenMarks: draft.written ?? null } : {}),
      trainerId: this.trainerId,
      skillMarks: Object.entries(draft.skills).map(([skillId, marks]) => ({
        skillId: Number(skillId),
        marks: marks ?? 0,
        /* An emptied box takes the mark back rather than recording a zero. */
        clear: marks === null,
      })),
    }));

    this.saving.set(true);
    this.service.save(sheet.programmeId, { rows }).subscribe({
      next: (saved) => {
        this.saving.set(false);
        this.drafts.set({});
        this.sheet.set(saved);
        this.toast.success(
          'Marks saved',
          `${saved.passCount} passed, ${saved.failCount} did not qualify.`,
        );
      },
      error: () => this.saving.set(false),
    });
  }
}

/** An empty box is "not marked"; anything else is a number or it is ignored. */
function toMark(value: unknown): number | null {
  if (value === null || value === undefined || value === '') return null;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : null;
}
